import Ember from 'ember';

export default Ember.Service.extend({
  optionalSkillsByNT:{
    NT1To4: [
        ['arcos','armas arrojadizas', 'armas a 1 mano', 'armas a 2 manos', 'ballestas'],
        ['etiqueta','montar', 'nadar'],
        ['supervivencia']],
    NT5: [
        ['arcos','armas arrojadizas', 'armas a 1 mano', 'armas de polvora', 'ballestas'],
        ['etiqueta','montar', 'nadar'],
        ['supervivencia']],
    NT6: [
        ['armas arrojadizas', 'armas cortas', 'armas largas', 'etiqueta'],
        ['conocimiento(Arte)','conocimiento (Historia)','ciencia (Biología)', 'ciencia (Física)', 'ciencia (Química)', 'computadora'],
        ['conducir vehículos (Ligeros)']],
    NT7To10: [
        ['armas cortas', 'armas largas', 'computadora','comunicaciones', 'etiqueta','sensores'],
        [ 'conocimiento (Arte)',
          'conocimiento (Geografía)',
          'conocimiento (Historia)',
          'conocimiento (Leyes)',
          'conocimiento (Lingüista)',
          'conocimiento (Psicología)',
          'conocimiento (Saber Arcano)',
          'conocimiento (Sociología)',
          'conocimiento (Teología)',
          'ciencia (Biología)',
          'ciencia (Física)',
          'ciencia (Forense)',
          'ciencia (Genética)',
          'ciencia (Geología)',
          'ciencia (informática)',
          'ciencia (Ingeniería)',
          'ciencia (Matemáticas)',
          'ciencia (Medicina)',
          'ciencia (Química)',
          'ciencia (Robótica)',
          'ciencia (Xenología)'],
        ['conducir vehículos(Ligeros)', 'pilotar (Aeronave)', 'pilotar (Astronave)']
    ]},
  skillsByNT:{
    NT1To4:[
    'Arcos',
    'Armas Arrojadizas',
    'Armas a 1 Mano',
    'Armas a 2 Manos',
    'Armas de Pólvora',
    'Armas Pesadas',
    'Averiguar Intenciones',
    'Ballestas',
    'Ciencia (Alquimia)',
    'Ciencia (Filosofía Natural)',
    'Ciencia (Ingeniería)',
    'Ciencia (Matemáticas)',
    'Ciencia (Medicina)',
    'Comunicaciones',
    'Voluntad',
    'Conducir Vehículo (Ligeros)',
    'Conocimiento (Arte)',
    'Conocimiento (Geografía)',
    'Conocimiento (Historia)',
    'Conocimiento (Leyes)',
    'Conocimiento (Lingüística)',
    'Conocimiento (Saber Arcano)',
    'Conocimiento (Teología)',
    'Delito',
    'Disfraz',
    'Engañar',
    'Esquivar',
    'Etiqueta',
    'Instrucción',
    'Intimidar',
    'Lenguajes',
    'Liderazgo',
    'Mecánica',
    'Montar',
    'Nadar',
    'Navegación',
    'Oficio (Especialidad)',
    'Persuadir',
    'Pilotar (Barcos)',
    'Primeros Auxilios',
    'Sigilo',
    'Supervivencia'
  ],
  NT5: ['Arcos','Armas Arrojadizas','Armas a 1 Mano', 'Armas a 2 Manos',
    'Armas de Pólvora',
    'Armas Pesadas','Averiguar Intenciones','Ballestas','Ciencia (Biología)',
    'Ciencia (Física)','Ciencia (Geología)','Ciencia (Ingeniería)',
    'Ciencia (Matemáticas)',
    'Ciencia (Medicina)',
    'Ciencia (Química)','Comunicaciones','Conducir Vehículo (Ligeros)',
    'Conocimiento (Arte)',
    'Conocimiento (Geografía)',
    'Conocimiento (Historia)',
    'Conocimiento (Leyes)',
    'Conocimiento (Lingüística)',
    'Conocimiento (Teología)',
    'Delito','Disfraz','Engañar',
    'Esquivar',
    'Etiqueta',
    'Instrucción',
    'Intimidar',
    'Lenguajes',
    'Liderazgo',
    'Mecánica',
    'Montar',
    'Nadar',
    'Navegación','Oficio (Especialidad)','Persuadir','Pilotar (Barcos)',
    'Primeros Auxilios','Sigilo',
    'Supervivencia'],
  NT6: ['Arcos','Armas Cortas',
    'Armas Cuerpo a Cuerpo','Armas Largas',
    'Armas Montadas','Armas Pesadas','Averiguar Intenciones',
    'Ciencia (Biología)','Ciencia (Física)','Ciencia (Forense)',
    'Ciencia (Genética)','Ciencia (Geología)', 'Ciencia (Informática)',
    'Ciencia (Ingeniería)',
    'Ciencia (Matemáticas)',
    'Ciencia (Medicina)','Ciencia (Química)','Ciencia (Robótica)',
    'Computadora','Comunicaciones','Conducir Vehículo (Ligeros)',
    'Conducir Vehículo (Pesados)',
    'Conocimiento (Antropología)',
    'Conocimiento (Arte)',
    'Conocimiento (Geografía)',
    'Conocimiento (Historia)',
    'Conocimiento (Leyes)',
    'Conocimiento (Lingüística)','Conocimiento (Psicología)',
    'Conocimiento (Sociología)','Conocimiento (Teología)',
    'Delito','Demoliciones','Disfraz','Electrónica','Engañar',
    'Esquivar',
    'Etiqueta',
    'Instrucción',
    'Intimidar',
    'Lenguajes',
    'Liderazgo',
    'Mecánica',
    'Montar',
    'Nadar',
    'Navegación','Observador','Oficio (Especialidad)','Persuadir',
    'Pilotar (Aeronave)','Pilotar (Barcos)','Pilotar (Submarinos)',
    'Primeros Auxilios','Sensores','Sigilo',
    'Supervivencia'],
  NT7To10: ['Arcos','Armas Cortas',
    'Armas Cuerpo a Cuerpo','Armas Largas',
    'Armas Montadas','Armas Pesadas','Averiguar Intenciones',
    'Ciencia (Biología)','Ciencia (Física)','Ciencia (Forense)',
    'Ciencia (Genética)','Ciencia (Geología)',
    'Ciencia (Informática)',
    'Ciencia (Ingeniería)',
    'Ciencia (Matemáticas)',
    'Ciencia (Medicina)','Ciencia (Química)','Ciencia (Robótica)',
    'Ciencia (Xenología)','Computadora','Comunicaciones',
    'Conducir Vehículo (Andadores)','Conducir Vehículo (Ligeros)',
    'Conducir Vehículo (Pesados)',
    'Conocimiento (Antropología)',
    'Conocimiento (Arte)',
    'Conocimiento (Geografía)',
    'Conocimiento (Historia)',
    'Conocimiento (Leyes)',
    'Conocimiento (Lingüística)','Conocimiento (Psicología)',
    'Conocimiento (Sociología)','Conocimiento (Teología)',
    'Delito','Demoliciones','Disfraz','Electrónica','Engañar',
    'Esquivar',
    'Etiqueta',
    'Instrucción',
    'Intimidar',
    'Lenguajes',
    'Liderazgo',
    'Mecánica',
    'Montar',
    'Nadar',
    'Navegación','Observador','Persuadir','Pilotar (Aeronave)',
    'Pilotar (Astronave)','Pilotar (Barcos)','Pilotar (Submarinos)',
    'Primeros Auxilios','Sensores','Sigilo',
    'Supervivencia']
  }
});
